### ISSUE TITLE
Typos in examples can be confusing

### ISSUE THREAD

**Issue by galpHub** [DiviProject/atomic-swaps#1]
At https://atomic-swaps.diviproject.org/api
"[string]secretHash
The secret hash (in hex bytes) to give a participant to redeem atomic swap funds."
Should say "to give the counterparty (or intended person) to participate in an atomic swap"

The 'participate' method should say [secretHash] instead of [secret]
$ atomicswap participate [address] [amount] [secret]
$ Do you want to publish this transaction? [y/N]
$ yes

Inside the 'redeem' function description there's a typo '[secret]hash' as opposed to '[string] secretHash'
[secret]hash
The secret hash that was created during an initiate or participate atomic swap HTTP call.

Other minor typos as well that will get caught in the next pass.

**Comment by ChrisCates** [comment]
Could you verbosely each piece of nomenclature that is incorrect on https://atomic-swaps.diviproject.org/api

Just specify it in this format:

1. endpoint (ie: `/v1/initiate`)
2. incorrect keys (ie: `secret should be secretHash`)

In a list, thank you!

**Comment by ChrisCates** [comment]
Several updates have been made, and various problems with nomenclature [as seen in the protofiles](https://github.com/DiviProject/atomic-swaps/tree/master/src/proto) should be resolved.
