### ISSUE TITLE
Direction of transaction feature & Atomic-Swap expiry feature request

### ISSUE THREAD

**Issue by galpHub** [DiviProject/atomic-swaps#2]
There's seems to be no ability to set an expiry date by which the refund should be triggered at the earliest. You should not be able to trigger a refund immediately, but you should also be able to specify such a minimum-time-till-refundable. Nobody will participate in an atomic swap if the counterparty can immediately exit their commitment.

Also, if you're locally running one full node of each, it seems hard to specify the direction of the trade. Perhaps some syntax like 'DIV > BTC' vs 'BTC > DIV' would help make it clear which transaction-direction you're participating in.

**Comment by ChrisCates** [comment]
Can review updates in `/src/proto`. The [protofiles](https://github.com/DiviProject/atomic-swaps/tree/master/src/proto) reflect this functionality now, with a `base` and `swap` keyword.
